backend:
 name: github
 repo: mikhail-cct/urban-jekyll-template # Path to your GitHub repository

media_folder: "images"

collections:
  - name: "website-settings"
    label: "Website settings"
    files:
      - label: "Website settings"
        name: "site"
        file: "_data/company.yml"
        fields:
          - label: "Title"
            name: "title"
            width: "string"
      - label: "Navigation"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - label: "Link"
            name: "links"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}
      - label: "Footer"
        name: "footer"
        file: "_data/footer.yml"
        fields:
          - name: "urls"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - label: "Links"
                name: "links"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Link", name: "link", widget: "string"}
                  - {label: "Social Icon", name: "social_icon", widget: "string"}
                  - {label: "New Window", name: "new_window", widget: "boolean"}